### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke function `zdr.index.iKAnalyzer`: Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by acm5656** [crazyyanchao/neo4j-graph-plugin#2]
RETURN zdr.index.iKAnalyzer('复联终章快上映了好激动，据说知识图谱与人工智能技术应用到了那部电影！吖啶基氨基甲烷磺酰甲氧基苯胺是一种药嘛？',true) AS words
你好，我在使用上述代码测试的时候遇到这个报错，请问怎么解决？
![image](https://user-images.githubusercontent.com/18107702/59774740-8bf71200-92e2-11e9-9381-8c8ba6c51429.png)
我的版本是3.5.6的。希望能收到你的回复，谢谢。

**Comment by crazyyanchao** [comment]
需要把dic目录放到neo4j的安装目录下

**Comment by crazyyanchao** [comment]
@acm5656 需要把dic目录放到neo4j的安装目录下
