### ISSUE TITLE
How to Automatic update the chinese Index？

### ISSUE THREAD

**Issue by jpfss** [crazyyanchao/neo4j-graph-plugin#3]
The cypher sequement as follows:
```sql
CALL zdr.index.addChineseFulltextAutoIndex('company',['companyName','formerName'],'Compnay',{autoUpdate:'true'}) YIELD message RETURN count(message) as optNum
```
And it does not work as the images as follows:
![image](https://user-images.githubusercontent.com/8890352/66365401-65f39b80-e9bf-11e9-8865-cf74e5c56e52.png)

**Comment by crazyyanchao** [comment]
看到报错是：Procedure Not Found!
插件包安装的可能不太对，你需要把JAR包放到plugin目录下。

**Comment by jpfss** [comment]
我看了源码，想用这个存储过程实现自动索引，关于“zdr.index.addChineseFulltextAutoIndex”存储过程给注释了，所以才没有的。如下图：
![image](https://user-images.githubusercontent.com/8890352/66373197-a1e82a00-e9da-11e9-88f7-03de70011bf3.png)
是不是目前这个插件不支持自动更新索引？

**Comment by crazyyanchao** [comment]
@jpfss 嗯，现在这个插件不支持中文索引自动更新

**Comment by jpfss** [comment]
嗯嗯，好的，谢谢！有能够查询意见通过"addChineseFulltextIndex"建立的索引的存储过程吗？
