### ISSUE TITLE
ik分词报null_pointer_exception

### ISSUE THREAD

**Issue by shenfl** [crazyyanchao/neo4j-graph-plugin#4]
我将neo4j的版本改成3.5.13后，执行：
RETURN zdr.index.iKAnalyzer('复联终章快上映了好激动，据说知识图谱与人工智能技术应用到了那部电影！吖啶基氨基甲烷磺酰甲氧基苯胺是一种药嘛？',true) AS words
报错：
Failed to invoke function `zdr.index.iKAnalyzer`: Caused by: java.lang.NullPointerException

**Comment by crazyyanchao** [comment]
https://github.com/crazyyanchao/neo4j-graph-plugin/issues/2
